CREATE USER IF NOT EXISTS'ReadOnlyUser'@'%' IDENTIFIED BY 'ReadOnlyPassword';
GRANT SELECT ON *.* TO 'ReadOnlyUser'@'%';
FLUSH PRIVILEGES;

CREATE SCHEMA IF NOT EXISTS `collector`;

CREATE TABLE IF NOT EXISTS `collector`.`measurements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `temp_in` FLOAT NOT NULL,
  PRIMARY KEY (`id`));
